# Generated by Django 3.2.2 on 2023-05-29 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tinkoff_payments', '0003_auto_20230529_1110'), ('tinkoff_payments', '0004_alter_tinkoffpaymentdata_created_at'), ('tinkoff_payments', '0005_alter_tinkoffpaymentdata_created_at')]

    dependencies = [
        ('tinkoff_payments', '0002_tinkoffpaymentdata_lifetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinkoffpaymentdata',
            name='lifetime',
        ),
        migrations.AddField(
            model_name='tinkoffpaymentdata',
            name='payment_session_lifetime',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='Payment session lifetime'),
        ),
        migrations.AddField(
            model_name='tinkoffpaymentdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
    ]
